### ISSUE TITLE
 The Docker environment relies on a missing resource

### ISSUE THREAD

**Issue by Leuchak** [clubcapra/rove#8]
The `.env` file is required but is missing from the environnement.
Either the file should not be required, or a default file (not a sample) should be supplied.

> [2023-12-10T21:58:10.895Z] Failed to load /<...>/rove/.env: open /<...>/.env: no such file or directory

**Comment by SimonR99** [comment]
There is a sample.env in the repo, we just need to add a section about it in the readme. (copy the sample.env and remove the sample). I'll add the tag good first issue.

**Comment by SimonR99** [comment]
The instructions are already present in the section "work in a dev container". I just should be better written
